// Self-host the editorial fonts (issue #3, PR #22 review).
//
// The UI copy is Greek-first, but Newsreader / Hanken Grotesk ship no Greek
// glyphs. This pulls Greek-capable *variable* replacements straight from the
// Google Fonts css2 API and writes them into the repo so we don't depend on the
// Google CDN at runtime (per @mgiannopoulos24's review):
//
//   Literata       — editorial serif headings (variable opsz+wght, roman + italic)
//   Manrope        — body sans              (variable wght)
//   JetBrains Mono — mono labels            (variable wght)
//
// All three are SIL OFL 1.1. Only the subsets we actually render are kept
// (latin, latin-ext, greek); each subset stays its own @font-face + unicode-range
// so a page only downloads the glyphs it needs.
//
// Run from the `frontend/` dir:  node scripts/fetch-fonts.mjs

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const ALLOWED = new Set(['latin', 'latin-ext', 'greek']);

const FAMILIES = [
  {
    name: 'Literata',
    slug: 'literata',
    spec: 'Literata:ital,opsz,wght@0,7..72,200..900;1,7..72,200..900',
  },
  { name: 'Manrope', slug: 'manrope', spec: 'Manrope:wght@200..800' },
  { name: 'JetBrains Mono', slug: 'jetbrains-mono', spec: 'JetBrains+Mono:wght@100..800' },
];

const here = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(here, '..', 'public', 'fonts');
const cssOut = join(here, '..', 'src', 'fonts.css');

/** Split css2 output into { subset, block } pairs (each @font-face is preceded by a `/* subset *​/` comment). */
function parseBlocks(css) {
  const out = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g;
  let m;
  while ((m = re.exec(css)) !== null) out.push({ subset: m[1], block: m[2] });
  return out;
}

const field = (block, name) => {
  const m = block.match(new RegExp(`${name}:\\s*([^;]+);`));
  return m ? m[1].trim() : '';
};

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.text();
}

await mkdir(fontsDir, { recursive: true });

const parts = [
  `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted variable fonts (issue #3, PR #22 review). All SIL OFL 1.1.
   Subsets: latin, latin-ext, greek (the UI copy is Greek-first).
   Regenerate with:  node scripts/fetch-fonts.mjs */`,
];

let saved = 0;
for (const fam of FAMILIES) {
  const css = await fetchText(
    `https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`,
  );
  for (const { subset, block } of parseBlocks(css)) {
    if (!ALLOWED.has(subset)) continue;
    const italic = field(block, 'font-style') === 'italic';
    const urlMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
    if (!urlMatch) continue;

    const file = `${fam.slug}${italic ? '-italic' : ''}-${subset}.woff2`;
    const bin = await fetch(urlMatch[1], { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`GET ${urlMatch[1]} -> ${bin.status}`);
    const buf = Buffer.from(await bin.arrayBuffer());
    await writeFile(join(fontsDir, file), buf);

    const local = block
      .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('/fonts/${file}')`)
      .replace(/\s*\n\s*/g, '\n  ')
      .replace('@font-face{', '@font-face {\n  ')
      .replace(/;}/, ';\n}');
    parts.push(`/* ${fam.name} · ${subset}${italic ? ' · italic' : ''} */\n${local}`);
    console.log(`  ${file.padEnd(34)} ${(buf.length / 1024).toFixed(1)} KB`);
    saved++;
  }
}

await writeFile(cssOut, parts.join('\n\n') + '\n');
console.log(`\nSaved ${saved} woff2 files -> public/fonts/`);
console.log(`Wrote ${cssOut.replace(join(here, '..'), '.')}`);
